### ISSUE TITLE
Mark EDP CD Pipeline Operator as a Capsule adopter

### ISSUE THREAD

**Issue by prometherion** [epam/edp-cd-pipeline-operator#18]
:wave: Dario here, Project Capsule maintainer!

We discovered thanks to several [cross-referenced issues](https://github.com/projectcapsule/capsule/issues/868) that EDP is relying on Capsule as a dependency, and we're happy that our project is empowering third tools and platforms with multi-tenancy!

We'd be delighted to have your project, or organization, marked as adopter in the related [file](https://github.com/projectcapsule/capsule/blob/main/ADOPTERS.md).

That file helps in creating more confidence and trust about the project, as well as recognize the efforts put in place by the maintainers in delivering free and open source code to anybody.

Sorry for the direct approach by using an issue, there's no Discussion tab in this repository: hope we can have a chat! 🤗

**Comment by NikolayMarusenko** [comment]
Hello @prometherion!

Apologies for the delayed response. I've submitted the relevant [pull request ](https://github.com/projectcapsule/capsule/pull/944)and it's awaiting approval. Please inform me if any additional information is required.

Thank you.

**Comment by prometherion** [comment]
Thanks a lot, glad you're using Capsule!

Closing this issue since I've just merged the adopter PR! 🤗
